name: CI for hugo site

on:
  workflow_dispatch

env:
  HUGO_VERSION: '0.97.3'
  HUGO_CACHEDIR: /tmp/hugo_cache
  GO_VERSION: '1.15'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - uses: actions/setup-go@v3.0.0
        with:
          go-version: '${{ env.GO_VERSION }}'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.5.0
        with:
          hugo-version: "${{ env.HUGO_VERSION }}"
          extended: true

      - name: Setup hugo module cache
        uses: actions/cache@v3.0.1
        with:
          path: ${{ env.HUGO_CACHEDIR }}
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Build the site with hugo
        run: hugo --minify

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
            branch: gh-pages # The branch the action should deploy to.
            folder: public # The folder the action should deploy.
            target-folder: . # the root of the repo
            single-commit: true # only save the last commit on the deploy branch
