name: CI for hugo site

on:
  workflow_dispatch

env:
  HUGO_VERSION: '0.126.0'
  HUGO_CACHEDIR: /tmp/hugo_cache
  GO_VERSION: '1.22.0'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          
      - uses: actions/setup-go@v5
        with:
          go-version: '${{ env.GO_VERSION }}'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.0.0
        with:
          hugo-version: "${{ env.HUGO_VERSION }}"
          extended: true

      - name: Setup hugo module cache
        uses: actions/cache@v4
        with:
          path: ${{ env.HUGO_CACHEDIR }}
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Build the site with hugo
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
